version: '3.7'

services:
  blog:
    container_name: blog_app
    build:
      context: ./mysite/
      dockerfile: Dockerfile
    command: "python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    restart: always
    volumes:
      - ./mysite/:/mysite
    depends_on:
      - blog-db
    ports:
      - 2501:8000
    networks:
      - roiback-net
  blog-db:
    image: postgres
    container_name: blog_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - roiback-net

volumes:
  db-data:

networks:
  roiback-net:
    driver: bridge