# Generated by Django 3.1.5 on 2021-01-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deactivate_date',
            field=models.DateTimeField(null=True),
        ),
    ]
